//! Scaffold rendering pipeline.
//!
//! The full Markdown→Typst emitter, image pipeline, and mermaid sub-renderer
//! land in subsequent Work items. This scaffold:
//!
//! 1. Validates the input file exists and is readable.
//! 2. Reads the Markdown source (currently unused beyond surfacing the
//!    filename in the placeholder PDF).
//! 3. Compiles a tiny embedded Typst document referencing Twemoji Mozilla
//!    so the bundled font is exercised end-to-end.
//! 4. Writes the resulting PDF bytes next to the input.
//!
//! The `--strict` flag is wired into the pipeline signature so the
//! upcoming image-pipeline Work can elevate warnings without re-shaping
//! `main.rs`.

mod world;

use std::path::Path;

use crate::error::{Md2PdfError, Result};
use crate::pipeline::world::ScaffoldWorld;

/// Inputs to a single render run.
pub struct RenderRequest<'a> {
    pub input: &'a Path,
    pub output: &'a Path,
    /// Per D-b53937: when true, image-load warnings (and other
    /// warning-class behaviors named in §2 of that Decision) are
    /// elevated to exit code 6 and no PDF is written. The scaffold has
    /// no warning sources yet, so this flag is recorded but inert.
    pub strict: bool,
}

/// Run the (currently placeholder) render pipeline.
pub fn render(req: &RenderRequest<'_>) -> Result<()> {
    // 1. Input validation — exit 1 surface.
    if !req.input.exists() {
        return Err(Md2PdfError::InputNotFound {
            path: req.input.to_path_buf(),
        });
    }
    if !req.input.is_file() {
        return Err(Md2PdfError::InputNotFound {
            path: req.input.to_path_buf(),
        });
    }
    let _markdown_source =
        std::fs::read_to_string(req.input).map_err(|source| Md2PdfError::InputRead {
            path: req.input.to_path_buf(),
            source,
        })?;

    // 2. Strict mode — currently no warning sources to escalate. Once
    // the image pipeline lands (separate Work), the warning accumulator
    // hangs off the World / pipeline context and is checked here.
    let _ = req.strict;

    // 3. Build a Typst World with the bundled fonts and a placeholder
    // document, then compile and export.
    let display_name = req
        .input
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "<unnamed>".to_string());

    let typst_source = scaffold_document(&display_name);
    let world = ScaffoldWorld::new(typst_source);

    let document = typst::compile(&world)
        .output
        .map_err(|errors| Md2PdfError::TypstCompile(format_diags(&errors)))?;

    let pdf_options = typst_pdf::PdfOptions::default();
    let pdf_bytes = typst_pdf::pdf(&document, &pdf_options)
        .map_err(|errors| Md2PdfError::TypstCompile(format_diags(&errors)))?;

    // 4. Write the PDF next to the input.
    std::fs::write(req.output, pdf_bytes).map_err(|source| Md2PdfError::PdfWrite {
        path: req.output.to_path_buf(),
        source,
    })?;
    Ok(())
}

/// Tiny Typst document that exercises the bundled Twemoji Mozilla font.
/// The body deliberately includes a color emoji so a human inspecting
/// the scaffold PDF can confirm the COLRv0 wiring is live.
fn scaffold_document(input_name: &str) -> String {
    // Escape backslashes and quotes for safe embedding inside a Typst
    // string literal.
    let escaped = input_name.replace('\\', "\\\\").replace('"', "\\\"");
    format!(
        r#"#set page(width: 8.5in, height: 11in, margin: 1in)
#set text(size: 14pt)

= md2pdf scaffold

This is a placeholder PDF generated by the v1 scaffold (Work W-1bab5f).
The Markdown→Typst emitter, image pipeline, and mermaid sub-renderer
land in subsequent Work items.

Input file: *{escaped}*

Bundled emoji font (Twemoji Mozilla, COLRv0): 😀 🎉 ✨ 🚀
"#
    )
}

fn format_diags<C>(diags: &C) -> String
where
    for<'a> &'a C: IntoIterator<Item = &'a typst::diag::SourceDiagnostic>,
{
    let mut out = String::new();
    for d in diags {
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&d.message);
    }
    if out.is_empty() {
        out.push_str("(no diagnostics)");
    }
    out
}
